### ISSUE TITLE
Current project doesn't work with listed requirements

### ISSUE THREAD

**Issue by acidjunk** [feinheit/zipfelchappe#43]
When starting the webserver:

> from mptt.models import MPTTModel
> ImportError: No module named mptt.models

When I install latetst mptt : django version goes to 1.9.6. So I tried to install django-mptt<=0.7.4 but then I receive an error about Models not loaded yet.

>   File "/Users/acidjunk/.virtualenvs/test/lib/python2.7/site-packages/django/apps/registry.py", line 131, in check_models_ready
>     raise AppRegistryNotReady("Models aren't loaded yet.")

Any help is appreciated. I'm trying to get zipfelchappe running on a more modern 1.8 LTS stack also; but it would be handy if i can click around the older app.

**Comment by acidjunk** [comment]
For clarity: I'm trying to run the project straight from this repo in a venv with: pip install -r requirements.txt

**Comment by matthiask** [comment]
Yes, updating mptt (with `pip install -U` also updates Django). You could try explicitly installing some versions by hand, i.e.

`pip install "Django<1.8"; pip install "django-mptt<0.8"` etc.
